### ISSUE TITLE
for U flag wrong rate is showing while scan etds file

### ISSUE THREAD

**Issue by Pratishtha-9106253** [Newgen-Digitalworks-Private-Ltd/fastfact-desktop-DNF#18]
After scan etds file showing below default for short deduction
![image](https://github.com/user-attachments/assets/cbb5d7c5-3a07-455a-a288-0ef213df4a04)
[MUMI06277F_26Q_Q1_202425_2472024.xls](https://github.com/user-attachments/files/16363216/MUMI06277F_26Q_Q1_202425_2472024.xls)

**Comment by anuradhasulakhe** [comment]
Shared the patch
