### ISSUE TITLE
DNF 23-24 is not working

### ISSUE THREAD

**Issue by Noopur-9107085** [Newgen-Digitalworks-Private-Ltd/fastfact-desktop-DNF#3]
![image](https://github.com/Newgen-Digitalworks-Private-Ltd/fastfact-desktop-DNF/assets/128368696/933ea4e0-5cce-4f98-b897-7c199f0c5a9d)

**Comment by Noopur-9107085** [comment]
- Received Dnf.exe from Rajeshwari
- The exe is not working in eTdsDnf2324 folder
- It is working fine in eTdsDnf2223 when we rename the folder as eTdsDnf2324
- Need to check with Kiran sir

**Comment by anuradhasulakhe** [comment]
Shared the patch

**Comment by Noopur-9107085** [comment]
Received patch>>Patch is working fine
