### ISSUE TITLE
DNF is showing error for 24_Q4

### ISSUE THREAD

**Issue by Noopur-9107085** [Newgen-Digitalworks-Private-Ltd/fastfact-desktop-DNF#4]
![image](https://github.com/Newgen-Digitalworks-Private-Ltd/fastfact-desktop-DNF/assets/128368696/3dcfe42f-d399-4dd5-bf0b-65b7f23ddd40)

**Comment by anuradhasulakhe** [comment]
in SalarySlab.xml need  data for N Category

**Comment by anuradhasulakhe** [comment]
Shared the DNF patch to Noopur
