### ISSUE TITLE
Pan verification is not working on etdsdnf2324

### ISSUE THREAD

**Issue by Noopur-9107085** [Newgen-Digitalworks-Private-Ltd/fastfact-desktop-DNF#5]
![image](https://github.com/Newgen-Digitalworks-Private-Ltd/fastfact-desktop-DNF/assets/128368696/23e7e3a4-dcff-4b23-b150-faff1616ec88)
need to add latest traces.exe in etdsdnf2324

**Comment by Noopur-9107085** [comment]
patch received

**Comment by Noopur-9107085** [comment]
after replacing the patch


![Image](https://github.com/Newgen-Digitalworks-Private-Ltd/fastfact-desktop-DNF/assets/128368696/5504e029-1b02-4ddb-95b6-07d317f61d7c)

**Comment by anuradhasulakhe** [comment]
Shared the patch
