### ISSUE TITLE
Need to add traces login in DNF 2324

### ISSUE THREAD

**Issue by Noopur-9107085** [Newgen-Digitalworks-Private-Ltd/fastfact-desktop-DNF#9]

**Comment by Noopur-9107085** [comment]
Demo is done and share the files

**Comment by anuradhasulakhe** [comment]
shared the patch for testing

**Comment by Noopur-9107085** [comment]
![Image](https://github.com/Newgen-Digitalworks-Private-Ltd/fastfact-desktop-DNF/assets/128368696/b2edaa77-b05a-4390-b7f2-c27fe7262ba9)

**Comment by Noopur-9107085** [comment]
![Image](https://github.com/Newgen-Digitalworks-Private-Ltd/fastfact-desktop-DNF/assets/128368696/a4da5fd3-76dd-4007-80a7-f75d821a9ad5)

Working fine but need to import pan's on excel file.

**Comment by anuradhasulakhe** [comment]
Shared the patch  for Pan Verification  Export to Excel
